language: php
matrix:
  include:
  - php: 7.2
    env: PREFER_LOWEST=""
  - php: 7.1
    env: PREFER_LOWEST=""

cache:
  directories:
  - doc/doc-en
  - vendor
  - $HOME/.composer

before_script:
- composer install --no-interaction
- mkdir -p build/logs
- |
  if [ ! -d "doc/doc-en/en" ]; then
    cd doc
    svn co https://svn.php.net/repository/phpdoc/modules/doc-en doc-en --quiet
    cd ..
  else
    cd doc/doc-en
    svn update
    cd ../..
  fi

script:
- "./vendor/bin/phpunit"
#- "./vendor/bin/composer-require-checker --config-file=composer-require-checker.json"
- composer cs-check
- composer phpstan
# Now, let's regenerate all files and see if we obtain the same set of files as the ones commited:
- ./safe.php generate
- |
  if output=$(git status --porcelain) && [ -z "$output" ]; then
    # all is good
    echo "Generated files are the same as committed file: OK"
  else
    # Uncommitted changes
    echo "Generated files are different from commited files. Please run './safe.php generate' command and commit the results."
    exit 1;
  fi
after_script:
- travis_retry php vendor/bin/php-coveralls
