language: php
matrix:
  include:
  - php: 7.2
    env: PREFER_LOWEST=""
  - php: 7.1
    env: PREFER_LOWEST=""
#  - php: 7.1
#    env: PREFER_LOWEST="--prefer-lowest"

cache:
  directories:
  - doc/doc-en


before_script:
- composer update $PREFER_LOWEST --no-interaction
- mkdir -p build/logs
- |
  if [ ! -d "doc/doc-en" ]; then
    cd doc
    svn co https://svn.php.net/repository/phpdoc/modules/doc-en doc-en
    cd ..
  else
    cd doc/doc-en
    svn update
    cd ../..
  fi

script:
- "./vendor/bin/phpunit"
#- "./vendor/bin/composer-require-checker --config-file=composer-require-checker.json"
- composer cs-check
- composer phpstan
after_script:
- travis_retry php vendor/bin/php-coveralls
