language: php
matrix:
  include:
  - php: 7.2
    env: PREFER_LOWEST=""
  - php: 7.1
    env: PREFER_LOWEST=""

cache:
  directories:
  - generator/doc/doc-en
  - vendor
  - $HOME/.composer

before_script:
- cd generator && composer install --no-interaction && cd ..
- |
  if [ ! -d "generator/doc/doc-en/en" ]; then
    cd generator/doc
    svn co https://svn.php.net/repository/phpdoc/modules/doc-en doc-en
    cd ../..
  else
    cd generator/doc/doc-en
    svn update
    cd ../../..
  fi
- composer update

script:
- cd generator && ./vendor/bin/phpunit && cd ..
- cd generator && composer cs-check && cd ..
- cd generator && composer phpstan && cd ..
- composer cs-check
- composer phpstan

after_script:
- travis_retry php vendor/bin/php-coveralls
